SELECT
  BILLADDR1 AS billAddress1,
  BILLADDR2 AS billAddress2,
  BILLCITY,
  BILLCOUNTRY,
  BILLSTATE,
  BILLTOFIRSTNAME,
  BILLTOLASTNAME,
  BILLZIP,
  SHIPADDR1 AS shipAddress1,
  SHIPADDR2 AS shipAddress2,
  SHIPCITY,
  SHIPCOUNTRY,
  SHIPSTATE,
  SHIPTOFIRSTNAME,
  SHIPTOLASTNAME,
  SHIPZIP,
  CARDTYPE,
  COURIER,
  CREDITCARD,
  EXPRDATE AS expiryDate,
  LOCALE,
  ORDERDATE,
  ORDERS.ORDERID,
  TOTALPRICE,
  USERID AS username,
  STATUS
FROM ORDERS, ORDERSTATUS
WHERE ORDERS.USERID = /*username*/'username'
  AND ORDERS.ORDERID = ORDERSTATUS.ORDERID
ORDER BY ORDERDATE